name: Publish

on:
  release:
    types:
      - published

env:
  REPOSITORY_URL: https://github.com/olivergregorius/raspberrypi4-uefi

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Set Up Build Environment
        run: |
          sudo apt update
          sudo apt install gcc-aarch64-linux-gnu acpica-tools

      - name: Checkout Submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build UEFI
        run: |
          cd edk2-platform
          git apply ../auto_boot_pxe_after_boot_failure.patch
          git apply ../rpi4_default_device_settings_change.patch
          cd ..
          git apply ../rpi4_default_device_settings_change.patch
          export WORKSPACE=$PWD
          export PACKAGES_PATH=$WORKSPACE/edk2:$WORKSPACE/edk2-platforms:$WORKSPACE/edk2-non-osi
          source edk2/edksetup.sh
          make -C edk2/BaseTools
          NUM_CPUS=$((`getconf _NPROCESSORS_ONLN` + 2))
          GCC5_AARCH64_PREFIX=aarch64-linux-gnu- build -n $NUM_CPUS -a AARCH64 -t GCC5 -b RELEASE -p edk2-platforms/Platform/RaspberryPi/RPi4/RPi4.dsc --pcd gEfiMdeModulePkgTokenSpaceGuid.PcdFirmwareVendor=L"${{ env.REPOSITORY_URL }}" --pcd gEfiMdeModulePkgTokenSpaceGuid.PcdFirmwareVersionString=L"UEFI Firmware ${{ github.ref_name }}"
          cp Build/RPi4/RELEASE_GCC5/FV/RPI_EFI.fd .

      - name: Download Raspberry Pi 4 Firmware
        run: |
          curl -O -L https://github.com/raspberrypi/firmware/raw/master/boot/fixup4.dat
          curl -O -L https://github.com/raspberrypi/firmware/raw/master/boot/start4.elf
          curl -O -L https://github.com/raspberrypi/firmware/raw/master/boot/bcm2711-rpi-4-b.dtb
          curl -O -L https://github.com/raspberrypi/firmware/raw/master/boot/overlays/gpio-shutdown.dtbo
          curl -O -L https://github.com/raspberrypi/firmware/raw/master/boot/overlays/disable-bt.dtbo
          mkdir overlays
          mv *.dtbo overlays

      - name: Zip UEFI
        run: zip -r RaspberryPi4_UEFI_${{ github.ref_name }}.zip RPI_EFI.fd fixup4.dat start4.elf bcm2711-rpi-4-b.dtb overlays config.txt README.md

      - name: Upload UEFI Archive To Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: RaspberryPi4_UEFI_${{ github.ref_name }}.zip
          asset_name: RaspberryPi4_UEFI_${{ github.ref_name }}.zip
          asset_content_type: application/octet-stream
